newstopia/newstopia/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^articles/', include('articles.urls', namespace="articles")),
    url(r'^account/', include('authentication.urls', namespace="account")),
    url(r'^tags/', include('tags.urls', namespace="tags")),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()

newstopia/tags/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from tags import views

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^(?P<pk>\d+)/$', views.detail, name='detail'),
                       url(r'^(?P<pk>\d+)/edit/$', views.edit, name='edit'),
                       url(r'^add/$', views.create, name='create'),
                       )

newstopia/tags/models.py
from django.db import models

class Tag(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=200)

newstopia/tags/views.py
from django.shortcuts import render, render_to_response
from tags.models import Tag

def index(request):
    tags = Tag.objects.all().order_by('-name')
    return render(request, 'tags/index.html', {'tags': tags})

def detail(request, pk):
    tag = Tag.objects.get(pk=pk)
    return render(request, 'tags/detail.html', {'tag': tag})

def edit(request, pk):
    tag = Tag.objects.get(pk=pk)
    if request.method == 'POST':
        tag.name = request.POST['name']
        tag.save()
        return render_to_response('tags/detail.html', {'tag': tag})
    else:
        return render(request, 'tags/edit.html', {'tag': tag})

def create(request):
    valid = True
    if request.method == 'POST':
        if request.POST['name'] == "":
            valid = False
    if request.method == 'POST' and valid:
        tag = Tag(name=request.POST['name'])
        tag.save()
        return render_to_response('tags/detail.html', {'tag': tag})
    else:
        return render(request, 'tags/create.html', {'valid': valid})

newstopia/tags/templates/tags/create.html
<form method="post" action="">
    {% csrf_token %}
    Name: <input type="text" name="name"><br>
    <input type="submit" value="Save">
    {% if not valid %}
        <b>Form not valid, fill in the field</b>
    {% endif %}
</form>

newstopia/tags/templates/tags/detail.html
<h1>{{tag.name}}</h1>
    <a href="{% url 'tags:edit' tag.pk %}">Edit</a>

newstopia/tags/templates/tags/edit.html
<h1>{{ tag.name }}</h1>
        <form action="" method="post">
            {% csrf_token %}
            Name: <input type="text" name="name" value="{{tag.name}}"><br>
            <input type="submit" value="Save">
        </form>

newstopia/tags/templates/tags/index.html
<h1>Tags</h1>
        <a href="{% url 'tags:create' %}">New tag</a>
{% for tag in tags %}
        <p>
            <h3><a href="{% url 'tags:detail' tag.pk %}">{{ tag.name }}</a></h3>
        </p>
{% endfor %}