newstopia/articles/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from articles import views

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^(?P<pk>\d+)/$', views.detail, name='detail'),
                       url(r'^add/$', views.create, name='create'),
                       url(r'^about/$', views.about, name='about'),
                       url(r'^vote/$', views.vote, name='vote'),
                       url(r'^archive/$', views.archive, name='archive'),
                       url(r'^faq/$', views.faq, name='faq'),
                       ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()

newstopia/authentication/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from authentication import views

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', views.profile, name='profile'),
                       url(r'^profile/$', views.profile, name='profile'),
                       url(r'^login/$', views.acclogin, name='login'),
                       url(r'^register/$', views.registration, name='register'),
                       url(r'^logout/$', views.acclogout, name='logout'),
                       )

newstopia/newstopia/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^articles/', include('articles.urls', namespace="articles")),
    url(r'^account/', include('authentication.urls', namespace="account")),
    url(r'^tags/', include('tags.urls', namespace="tags")),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()

newstopia/tags/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from tags import views

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^(?P<pk>\d+)/$', views.detail, name='detail'),
                       url(r'^(?P<pk>\d+)/edit/$', views.edit, name='edit'),
                       url(r'^add/$', views.create, name='create'),
                       )

newstopia/articles/models.py
import datetime
from django.db import models
from django.utils import timezone
from authentication.models import Contributor

class Article(models.Model):
    def __str__(self):
        return self.title

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    rating = models.IntegerField(default=0)

    author = models.ForeignKey(Contributor)

class Paragraph(models.Model):
    def __str__(self):
        return self.text

    article = models.ForeignKey(Article)
    text = models.CharField(max_length=9999)
    rating = models.IntegerField(default=0)
    author = models.ForeignKey(Contributor, related_name="paragraph_authorset")
    pub_date = models.DateTimeField('date published')

class Paragraph_Likes(models.Model):
    user = models.ForeignKey(Contributor, related_name="paragraph_likes_userset")
    paragraph = models.ForeignKey(Paragraph, related_name="paragraph_likes_paragraphset")

class Article_Likes(models.Model):
    user = models.ForeignKey(Contributor, related_name="article_likes_userset")
    article = models.ForeignKey(Article, related_name="article_likes_articleset")

class Tags(models.Model):
    name = models.CharField(max_length=128)

class Article_Tags(models.Model):
    article = models.ForeignKey(Article)
    tag = models.ForeignKey(Tags)
    value = models.IntegerField(default=0)

newstopia/articles/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.http import HttpResponse
from articles.models import Article, Paragraph, Article_Likes, Paragraph_Likes, Tags, Article_Tags
from datetime import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

def index(request):
    class Articledata(object):
        def __init__(self, **kwargs):
            self.__dict__.update(kwargs)

    class Paragraphdata(object):
        def __init__(self, **kwargs):
            self.__dict__.update(kwargs)

    articles = Article.objects.all().order_by('-pub_date')
    articlesData = []
    searchFound = []

    if request.method == 'POST':
        if request.POST['searchString']:
            search = request.POST['searchString']
            searchFound = []
            articlesData = []

            for a in articles:
                articleData = Articledata(article = a,
                                          isAuthor = request.user.is_authenticated() and a.author == request.user,
                                          hasLiked = True,
                                          paragraphs = [],
                                          article_resize = False,
                                          singleParagraph = False,
                                          )
                #Test for authentication, if not disregard likes
                if request.user.is_authenticated():
                    try:
                        Article_Likes.objects.get(user=request.user.email,
                                                  article=a)
                    except ObjectDoesNotExist:
                        articleData.hasLiked = False
                paragraphs = Paragraph.objects.filter(article=a).order_by('-rating')[0:5]
                amountParagraphs = Paragraph.objects.filter(article=a).order_by('-rating')[0:5].count()
                if amountParagraphs == 1:
                    articleData.singleParagraph = True
                if amountParagraphs > 3:
                    articleData.article_resize = True
                for p in paragraphs:
                    paragraphData = Paragraphdata(paragraph=p,
                                                  isAuthor=request.user.is_authenticated() and p.author == request.user.email,
                                                  hasLiked=True)

                    #Test for authentication, if not disregard likes
                    if request.user.is_authenticated():
                        try:
                            Paragraph_Likes.objects.get(user=request.user.email,
                                                        paragraph=p)
                        except ObjectDoesNotExist:
                            paragraphData.hasLiked = False

                    articleData.paragraphs.append(paragraphData)
                articlesData.append(articleData)

            for a in articlesData:
                if search[0] == '#':
                    text = search.replace("#", "")
                    text = text.replace(" ", "")
                    articleTags = Article_Tags.objects.filter(article=a.article)
                    for at in articleTags:
                        if at.tag.name == text:
                            searchFound.append(a)
                if search.lower() in a.article.title.lower():
                    if a not in searchFound:
                        searchFound.append(a)
                for p in a.paragraphs:
                    if search.lower() in p.paragraph.text.lower():
                        if a not in searchFound:
                            searchFound.append(a)

            articlesData = []

    for a in articles:
        articleData = Articledata(article = a,
                isAuthor = request.user.is_authenticated() and a.author == request.user,
                hasLiked = True,
                paragraphs = [],
                article_resize = False,
                singleParagraph = False
                )
        #Test for authentication, if not disregard likes
        if request.user.is_authenticated():
            try:
                Article_Likes.objects.get(user=request.user.email,
                                          article=a)
            except ObjectDoesNotExist:
                articleData.hasLiked = False
        paragraphs = Paragraph.objects.filter(article=a).order_by('-rating')[0:5]
        amountParagraphs = Paragraph.objects.filter(article=a).order_by('-rating')[0:5].count()
        if amountParagraphs == 1:
            articleData.singleParagraph = True
        if amountParagraphs > 3:
            articleData.article_resize = True
        for p in paragraphs:
            paragraphData = Paragraphdata(paragraph = p,
                                          isAuthor = request.user.is_authenticated() and p.author == request.user.email,
                                          hasLiked = True)

            #Test for authentication, if not disregard likes
            if request.user.is_authenticated():
                try:
                    Paragraph_Likes.objects.get(user=request.user.email,
                                                paragraph=p)
                except ObjectDoesNotExist:
                    paragraphData.hasLiked = False

            articleData.paragraphs.append(paragraphData)
        articlesData.append(articleData)

    if searchFound:
                articlesData = searchFound

    return render(request, 'articles/index.html', {'authenticated': request.user.is_authenticated(), 'user': request.user, 'articlesData': articlesData})

def detail(request, pk):
    class Articledata(object):
        def __init__(self, **kwargs):
            self.__dict__.update(kwargs)

    class Paragraphdata(object):
        def __init__(self, **kwargs):
            self.__dict__.update(kwargs)

    if request.user.is_authenticated():
        if request.method == 'POST':
            if request.POST['new_paragraph']:
                p = Paragraph(article=Article.objects.get(pk=pk),
                              text=request.POST['new_paragraph'],
                              rating=0,
                              author=request.user,
                              pub_date=datetime.now())
                p.save()


    article = Article.objects.get(pk=pk)
    articleData = Articledata(article = article,
            isAuthor = request.user.is_authenticated() and article.author == request.user.email,
            hasLiked = True,
            paragraphs = [])

    if request.user.is_authenticated():
        try:
            Article_Likes.objects.get(user=request.user.email,
                                      article=article)
        except ObjectDoesNotExist:
            articleData.hasLiked = False
    paragraphs = Paragraph.objects.filter(article=article).order_by('-rating')
    for p in paragraphs:
        paragraphData = Paragraphdata(paragraph = p,
                                      isAuthor = request.user.is_authenticated() and p.author == request.user.email,
                                      hasLiked = True)
        if request.user.is_authenticated():
            try:
                Paragraph_Likes.objects.get(user=request.user.email,
                                            paragraph=p)
            except ObjectDoesNotExist:
                paragraphData.hasLiked = False

        articleData.paragraphs.append(paragraphData)

    tags = Article_Tags.objects.filter(article=article)
    tagData = []
    for a in tags:
        tagData.append(a)

    if request.method == 'GET' or not request.user.is_authenticated():
        return render(request, 'articles/detail.html', {'articleData': articleData,
                                                    'tagData': tagData, 'authenticated': request.user.is_authenticated()})
    elif request.method == 'POST':
        return render_to_response('articles/detail.html', {'articleData': articleData,
                                                    'tagData': tagData, 'authenticated': request.user.is_authenticated()}, context_instance=RequestContext(request))


def create(request):
    if not request.user.is_authenticated():
        return render(request, 'articles/create.html', {'authenticated':request.user.is_authenticated()})


    valid = False
    if request.method == 'GET':
        valid = True
    if request.method == 'POST':
        if request.POST['title'] != "":
            valid = True
        if request.POST['body'] != "":
            valid = True
    if request.method == 'POST' and valid:

        class Articledata(object):
            def __init__(self, **kwargs):
                self.__dict__.update(kwargs)

        class Paragraphdata(object):
            def __init__(self, **kwargs):
                self.__dict__.update(kwargs)

        article = Article(title=request.POST['title'], pub_date=datetime.now(), author=request.user)
        article.save()
        paragraph = Paragraph(article=article, text=request.POST['body'], author=request.user, pub_date=datetime.now())
        paragraph.save()
        tags = request.POST['tags']
        tagData = []
        if tags:
            tags = tags.replace(" ", "")
            tags = tags.replace("#", "")
            tags = tags.split(',')
        for i in tags:
            count = Tags.objects.filter(name=i).count()
            if count == 0:
                tag = Tags(name=i)
                tag.save()
                articleTag = Article_Tags(article=article, tag=Tags.objects.get(name=i))
                articleTag.save()
                tagData.append(articleTag)
            else:
                articleTag = Article_Tags(article=article, tag=Tags.objects.get(name=i))
                articleTag.save()
                tagData.append(articleTag)

        article = Article.objects.get(pk=article.pk)

newstopia/articles/templates/articles/about.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Newstopia</title>

    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/normalize.css">
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/main.css">
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/about.css">

    <script type="text/javascript" src="{{STATIC_URL}}js/jquery.min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/jquery.stickOnScroll.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/index.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/login.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/jquery.index.js"></script>
</head>
<body>
<div id="staticSearchBar" class="staticBar">
    <form name="search" method="post">
        {% csrf_token %}
        <a href=""><i id="searchCommit" class="fa fa-search"></i></a>
        <input id="searchInput" class="input" type="text" name="searchString" placeholder="search">
    </form>
</div>
{% if not authenticated %}
<div id="staticLoginBar" class="staticBar">
    <form name="login" method="post" action="{% url 'account:login' %}">
        {% csrf_token %}
        <div id="emailInput">
            <i class="fa fa-child"></i>
            <input class="input" type="text" name="username" placeholder="email">
        </div>
        <div id="passwordInput">
            <i class="fa fa-lock"></i>
            <input id="passwordField" class="input" type="password" name="password" placeholder="password">
        </div>

        <a id="submitLogin" class="btn">
            <i class="fa fa-user"></i>login</a>
        <a id="goToRegister" href="{% url 'account:register' %}">(I'm new here)</a>
    </form>
</div>
{% else %}
<div id="staticLoginBar" class="staticBar">
    <p>welcome {{user.email}} <a href="{% url 'account:logout'%}">logout</a></p>
</div>
{% endif %}
<div class="container">
    <div id="logo">
        <img alt="logo" src="{{STATIC_URL}}img/Logo-Newstopia.png"/>
    </div>
    <div id="staticNav">
        <nav>
            <div class="menuSplits">
                <div class="menu-btn">
                    <a class="first-link" href="{% url 'articles:index' %}">
                        <i id="menuHome" class="fa fa-home fa-2x"></i>
                    </a>
                    <a href="{% url 'articles:index' %}">
                        home
                    </a>
                </div>
                <div class="menu-btn">
                    <a class="first-link" href="{% url 'articles:about' %}">
                        <i id="menuAbout" class="fa fa-question fa-2x"></i>
                    </a>
                    <a href="{% url 'articles:about' %}">
                        about
                    </a>
                </div>
                <div id="menuSearch" class="menu-btn">
                    <a class="first-link" href="">
                        <i id="searchIcon" class="fa fa-search fa-2x"></i>
                    </a>
                    <a href="">
                        search
                    </a>
                </div>
            </div>
            <div class="menuSplits">
                <div class="menu-btn">
                    <a class="first-link" href="">
                        <i id="menuArchive" class="fa fa-archive fa-2x"></i>
                    </a>
                    <a href="{% url 'articles:archive' %}">
                        archive
                    </a>
                </div>
                <div class="menu-btn">
                    <a class="first-link" href="{% url 'articles:create' %}">
                        <i id="menuNewArticle" class="fa fa-pencil fa-2x"></i>
                    </a>
                    <a href="{% url 'articles:create' %}">
                        new article
                    </a>
                </div>
                <div id="{% if authenticated %}menuProfileL{% else %}menuProfile{% endif %}" class="menu-btn">
                    {% if authenticated %}
                    <a class="first-link" href="">
                        <i id="ProfileIcon" style="float:left;width:24px;height 32px;margin-left:24px;margin-top:-2px;" class="fa fa-user fa-2x"></i>

                        <h2 style="float:right;width:24px;height 32px;overflow:hidden;margin-top:2px;color:#568a8f;margin-right:15px;">{{ user.email|slice:":1" }}</h2>
                    </a>
                    <a style="float:left;text-align:center;width:90px;height:32px;margin-left:0px;margin-top:-20px;" href="{% url 'account:profile' %}">
                        profile
                    </a>
                    {% else %}
                    <a class="first-link" href="">
                        <i id="ProfileIcon" class="fa fa-user fa-2x"></i>
                    </a>
                    <a href="">
                        login
                    </a>
                    {% endif %}
                    </a>
                </div>
            </div>
        </nav>
    </div>
    <div id="aboutText">
        <p><b>Newstopia is about you.</b> It is created for people who are interested in the world, but are sick of the
            way it’s being
            represented. Ideally you’ll only find objective news here, generated by many different people.
            Ideally, yes, since this is an experiment, just like any other utopia.

        </p>

        <p>The only way the quality of the news on Newstopia will be affected is by the way you, me or anyone else
            treats
            it. If we
            collectively decide to use this platform to force opinions on others while neglecting proper fact checking and
            newsworthiness, we will have proven
            to be
            like any other news-platform. But if we collectively decide to value truth and objectivity this could be the dawning of a news age.</p>

        <p>So once again: it’s about you. Should you decide to use this platform as a way to create hate or fear, then
            it’s
            up
            to everyone else to make sure it doesn’t reach the front page. Conversely, should you decide to use it as a
            way
            to
            make the world a better place, it’s up to each and every one of us to make sure it stays up there.</p>

        <p>We're excited about it! For answers to your questions please check out our <a href="{% url 'articles:faq' %}">FAQ</a>-page
            and if you have any thoughts or comments on how we could do better give us a shout on email@newstopia.com.</p>



        <div id="aboutSocial">
            <i class="fa fa-facebook-square fa-2x"></i>
            <i class="fa fa-twitter-square fa-2x"></i>
            <i class="fa fa-git-square fa-2x"></i>
        </div>
    </div>
</div>
<!--masonry scripts-->
<script type="text/javascript" src="{{STATIC_URL}}js/masonry.pkgd.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/classie.js"></script>
</body>
</html>

newstopia/articles/templates/articles/create.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Newstopia</title>

    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/normalize.css">
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/main.css">
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/create.css">

    <script type="text/javascript" src="{{STATIC_URL}}js/jquery.min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/modernizr.custom.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/jquery.stickOnScroll.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/index.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/jquery.index.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/create.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/login.js"></script>
</head>

<body>
<div id="staticSearchBar" class="staticBar">
    <form name="search" method="post">
        {% csrf_token %}
        <a href=""><i id="searchCommit" class="fa fa-search"></i></a>
        <input id="searchInput" class="input" type="text" name="searchString" placeholder="search">
    </form>
</div>
{% if not authenticated %}
<div id="staticLoginBar" class="staticBar">
    <form name="login" method="post" action="{% url 'account:login' %}">
        {% csrf_token %}
        <div id="emailInput">
            <i class="fa fa-child"></i>
            <input class="input" type="text" name="username" placeholder="email">
        </div>
        <div id="passwordInput">
            <i class="fa fa-lock"></i>
            <input id="passwordField" class="input" type="password" name="password" placeholder="password">
        </div>
        <a id="submitLogin" class="btn">
            <i class="fa fa-user"></i>login</a>
        <a id="goToRegister" href="{% url 'account:register' %}">(I'm new here)</a>
    </form>
</div>
{% else %}
<div id="staticLoginBar" class="staticBar">
    <p>welcome {{user.email}} <a href="{% url 'account:logout'%}">logout</a></p>
</div>
{% endif %}
<div class="container">
    <div id="logo">
        <img alt="logo" src="{{STATIC_URL}}img/Logo-Newstopia.png"/>
    </div>
    <div id="staticNav">
        <nav>
            <div class="menuSplits">
                <div class="menu-btn">
                    <a class="first-link" href="{% url 'articles:index' %}">
                        <i id="menuHome" class="fa fa-home fa-2x"></i>
                    </a>
                    <a href="{% url 'articles:index' %}">
                        home
                    </a>
                </div>
                <div class="menu-btn">
                    <a class="first-link" href="{% url 'articles:about' %}">
                        <i id="menuAbout" class="fa fa-question fa-2x"></i>
                    </a>
                    <a href="{% url 'articles:about' %}">
                        about
                    </a>
                </div>
                <div id="menuSearch" class="menu-btn">
                    <a class="first-link" href="">
                        <i id="searchIcon" class="fa fa-search fa-2x"></i>
                    </a>
                    <a href="">
                        search
                    </a>
                </div>
            </div>
            <div class="menuSplits">
                <div class="menu-btn">
                    <a class="first-link" href="">
                        <i id="menuArchive" class="fa fa-archive fa-2x"></i>
                    </a>
                    <a href="{% url 'articles:archive' %}">
                        archive
                    </a>
                </div>
                <div class="menu-btn">
                    <a class="first-link" href="{% url 'articles:create' %}">
                        <i id="menuNewArticle" class="fa fa-pencil fa-2x"></i>
                    </a>
                    <a href="{% url 'articles:create' %}">
                        new article
                    </a>
                </div>
                <div id="{% if authenticated %}menuProfileL{% else %}menuProfile{% endif %}" class="menu-btn">
                    {% if authenticated %}
                    <a class="first-link" href="">
                        <i id="ProfileIcon" style="float:left;width:24px;height 32px;margin-left:24px;margin-top:-2px;" class="fa fa-user fa-2x"></i>

                        <h2 style="float:right;width:24px;height 32px;overflow:hidden;margin-top:2px;color:#568a8f;margin-right:15px;">{{ user.email|slice:":1" }}</h2>
                    </a>
                    <a style="float:left;text-align:center;width:90px;height:32px;margin-left:0px;margin-top:-20px;" href="{% url 'account:profile' %}">
                        profile
                    </a>
                    {% else %}
                    <a class="first-link" href="">
                        <i id="ProfileIcon" class="fa fa-user fa-2x"></i>
                    </a>
                    <a href="">
                        login
                    </a>
                        {% endif %}
                    </a>
                </div>
            </div>
        </nav>
    </div>
    {% if authenticated %}
    <div id="createContainer">
        <form name="newArticle" method="post" action="">
            {% csrf_token %}
            <input id="inputTitle" type="text" name="title" placeholder="write a title"><br>

            <textarea id="inputParagraph" name="body" maxlength="400" placeholder="compose the first paragraph" rows="5"
                      cols="35"></textarea>

            <textarea id="inputTags" rows="1" cols="20" maxlength="116" name="tags"
                      placeholder="give your article some tags (seperated by a comma)"></textarea><br>
            {% if not valid %}
            <b>form not valid, fill in both fields</b>
            {% endif %}
        </form>
        <div id="submitBtn" class="btn">
            <i class="fa fa-paper-plane"></i> submit
        </div>
    </div>
</div>
{% else %}
<div id="createContainer">
    You must be logged in in order to to create articles.
</div>
{% endif %}
</div>

<!--masonry scripts-->
<script type="text/javascript" src="{{STATIC_URL}}js/masonry.pkgd.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/classie.js"></script>

</body>

</html>

newstopia/articles/templates/articles/edit.html
<h1>{{ article.title }}</h1>
        <form action="" method="post">
            {% csrf_token %}
            <textarea rows="5" cols="50" name="body">{{article.body}}</textarea><br>
            <input type="submit" value="Bewaar">
        </form>